CANONICAL_HEX = {
    "yellow": "#FFD32A",
    "light yellow": "#FFF066",
    "dark yellow": "#B8860B",
    "muted yellow": "#E1C16E",
    "bright yellow": "#FFEA00",
    "pastel yellow": "#FFF3B0",
    "neon yellow": "#FFFF33",
    "orange": "#F39C12",
    "light orange": "#FFB347",
    "dark orange": "#FF8C00",
    "muted orange": "#E9967A",
    "bright orange": "#FFA500",
    "pastel orange": "#FFD2A6",
    "neon orange": "#FF5F1F",
    "red": "#E74C3C",
    "light red": "#FF6B6B",
    "dark red": "#8B0000",
    "muted red": "#CD5C5C",
    "bright red": "#FF0000",
    "deep red": "#8B0000",
    "neon red": "#FF3131",
    "pink": "#FFC0CB",
    "light pink": "#FFD6E0",
    "dark pink": "#FF69B4",
    "muted pink": "#D8A7B1",
    "bright pink": "#FF1493",
    "pastel pink": "#FFD1DC",
    "hot pink": "#FF69B4",
    "neon pink": "#FF44CC",
    "blue": "#3498DB",
    "light blue": "#ADD8E6",
    "dark blue": "#00008B",
    "muted blue": "#5D8AA8",
    "bright blue": "#1E90FF",
    "sky blue": "#87CEEB",
    "navy": "#2C3E50",
    "neon blue": "#1F51FF",
    "white": "#FFFFFF",
    "pure white": "#FFFFFF",
    "snow white": "#FAFAFA",
    "ivory": "#FFFFF0",
    "cream": "#FFFDD0",
    "off white": "#F8F8F8",
    "green": "#2ECC71",
    "light green": "#90EE90",
    "dark green": "#006400",
    "muted green": "#6B8E23",
    "bright green": "#00FF00",
    "mint green": "#98FF98",
    "pine green": "#01796F",
    "emerald": "#50C878",
    "neon green": "#39FF14",
    "brown": "#8D6E63",
    "light brown": "#C4A484",
    "dark brown": "#5C4033",
    "muted brown": "#A67B5B",
    "warm brown": "#8B5E3C",
    "chocolate brown": "#7B3F00",
    "mustard yellow": "#D4AF37",
    "gold": "#FFD700",
    "bronze": "#CD7F32",
    "charcoal black": "#333333",
    "black": "#000000",
    "jet black": "#0A0A0A",
    "burgundy": "#800020",
    "wine red": "#722F37",
    "lavender": "#E6DAF7",
    "violet": "#8E44AD",
    "dark violet": "#6F42C1",
    "purple": "#800080",
    "light purple": "#B19CD9",
    "neon purple": "#BC13FE",
    "apricot": "#FBCEB1",
    "peach": "#FFE5B4",
    "coral": "#FF7F50",
    "light gray": "#D3D3D3",
    "gray": "#B0B0B0",
    "dark gray": "#555555",
    "ash gray": "#B2BEB5",
    "slate gray": "#708090",
    "silver": "#C0C0C0"
}

ALIASES = {
    "노랑": "yellow",
    "연노랑": "light yellow",
    "진노랑": "dark yellow",
    "황토색": "mustard yellow",
    "네이비": "navy",
    "연보라": "lavender",
    "보라": "violet",
    "진보라": "dark violet",
    "보라색": "purple",
    "연보라색": "light purple",
    "살구색": "apricot",
    "피치": "peach",
    "산호색": "coral",
    "아이보리": "ivory",
    "크림색": "cream",
    "연분홍": "light pink",
    "분홍": "pink",
    "파스텔분홍": "pastel pink",
    "진분홍": "hot pink",
    "형광분홍": "neon pink",
    "연회색": "light gray",
    "회색": "gray",
    "진회색": "dark gray",
    "은색": "silver",
    "연백색": "snow white",
    "하양": "white",
    "흰색": "white",
    "검정": "black",
    "까만색": "black",
    "파스텔 옐로": "pastel yellow",
    "파스텔 오렌지": "pastel orange",
    "민트": "mint green",
    "하늘색": "sky blue",
    "진파랑": "dark blue",
    "형광파랑": "neon blue",
    "진빨강": "deep red",
    "형광빨강": "neon red",
    "파인그린": "pine green",
    "에메랄드": "emerald",
    "연초록": "light green",
    "진초록": "dark green",
    "형광초록": "neon green",
    "연주황": "light orange",
    "진주황": "dark orange",
    "형광주황": "neon orange",
    "연갈색": "light brown",
    "진갈색": "dark brown",
    "금색": "gold",
    "동색": "bronze",

    "mustard": "mustard yellow",
    "pastel-yellow": "pastel yellow",
    "pastel-orange": "pastel orange",
    "deepred": "deep red",
    "hotpink": "hot pink",
    "skyblue": "sky blue",
    "lightgrey": "light gray",
    "darkgrey": "dark gray",
    "snowwhite": "snow white",
    "pinegreen": "pine green",
    "mint": "mint green",
    "naviblue": "navy"
}


def normalize_color_name(name: str) -> str:
    key = (name or "").strip().lower()
    # alias → canonical
    key = ALIASES.get(key, key)
    return key

def to_hex(color_name: str) -> str:
    canon = normalize_color_name(color_name)
    return CANONICAL_HEX.get(canon, "#733DCB")  # 기본값
